# Generated by Django 4.1.1 on 2022-10-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matkul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=200)),
                ('kode', models.CharField(max_length=200)),
                ('mata_kuliah', models.CharField(max_length=200)),
                ('wp', models.CharField(max_length=200)),
                ('sks', models.CharField(max_length=200)),
            ],
        ),
    ]
